### ISSUE TITLE
Possible bug (git-changelog) - Contributors.vue import error. Failed import md5.

### ISSUE THREAD

**Issue by Ampernic** [nolebase/integrations#124]
I'm trying to use `@nolebase/vitepress-plugin-git-changelog` form `npm`

When i try add this in vite.config.ts this
```ts
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import UnoCSS from 'unocss/vite'
import { 
  GitChangelog,
  GitChangelogMarkdownSection 
} from '@nolebase/vitepress-plugin-git-changelog/vite'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

/* some other */ 

export default defineConfig({
  vite: {
    resolve: {
      alias: {
        '@nolebase/vitepress-plugin-git-changelog': resolve(__dirname, '/* path to npm package */ '),
      },
    },
    plugins: [
      UnoCSS(),
      GitChangelog({
        maxGitLogCount: 20000,
        repoURL: () => /* url */ ,
        rewritePaths: /* path */,
      }),
      GitChangelogMarkdownSection({
        getChangelogTitle: (_, __, { helpers }): string => {
          return /* title */
        },
        getContributorsTitle: (_, __, { helpers }): string => {
          return /* title */
        },
        excludes: [],
        exclude: (_, { helpers }): boolean => {
                /* some excludes or defauts, doesn't matter, this works normal */
        },
        sections: gitDisplay,
      }),
    ],
 /* another configs */
}
```

And add in theme/index.ts this:

```ts
import { 
  NolebaseGitChangelogPlugin
} from '@nolebase/vitepress-plugin-git-changelog/client'

/* some other imports */ 

export default {
  extends: DefaultTheme,
  Layout: () => {
    return h(DefaultTheme.Layout, null, {
      /* some own layout without using gitlog */ 
    })
  },
  enhanceApp(ctx) {
           /* some another plugins */ 
          ctx.app.use(NolebaseGitChangelogPlugin, {locales: /*locales*/ ,mapContributors: /* contibutors */ })
          enhanceAppWithTabs(ctx.app)
  },
```

I getting this in browser console:
![изображение](https://github.com/nolebase/integrations/assets/44705058/934ccf3d-7f12-4990-8702-672910ba93d8)
![изображение](https://github.com/nolebase/integrations/assets/44705058/8389dd92-5395-4e7c-a7d1-40a8c678fe00)
but md5 and @types/md5 or another permutations of this is installed...

Where is the problem?
Everything is working on version 1.23.0 and older, where /components has .vue.d.ts files, but 1.24.0 and newer not working.

Tested on:
vitepress: 1.0.0 rc 43/1.0.0 rc 45/1.0.1
git-changelog: 1.24.0-1.25.0

**Comment by nekomeowww** [comment]
Not sure where went wrong but one thing is clearly to be incorrect:

```diff
export default defineConfig({
  vite: {
    resolve: {
--      alias: {
--        '@nolebase/vitepress-plugin-git-changelog': resolve(__dirname, '/* path to npm package */ '),
--      },
    },
  },
}
```

Could you please try to remove the above configurations and try again?

For end users that import packages of Nolebase integrations from outside, no need to redirect `@nolebase/vitepress-plugin-git-changelog` or other `@nolebase` packages to `node_modules/` since we have bundled everything everyone needs when publishing the modules.

**Comment by Ampernic** [comment]
I tried this, but the picture remains the same

![изображение](https://github.com/nolebase/integrations/assets/44705058/8a59f100-72ac-48df-a10d-1716519d8575)


> It's nice to meet you here. And apologize for the lack of documentations we are having now. 😫
> 
> Not sure where went wrong but one thing is clearly to be incorrect:
> 
> ```diff
> export default defineConfig({
>   vite: {
>     resolve: {
> --      alias: {
> --        '@nolebase/vitepress-plugin-git-changelog': resolve(__dirname, '/* path to npm package */ '),
> --      },
>     },
>   },
> }
> ```
> 
> Could you please try to remove the above configurations and try again?
> 
> For end users that import packages of Nolebase integrations from outside, no need to redirect `@nolebase/vitepress-plugin-git-changelog` or other `@nolebase` packages to `node_modules/` since we have bundled everything everyone needs when publishing the modules.

**Comment by nekomeowww** [comment]
Weird. Thanks for the feedbacks. Let me try to inspect my other VitePress sites to figure out.

**Comment by Ampernic** [comment]
Thank you for fix, but can i ask about this after update
![изображение](https://github.com/nolebase/integrations/assets/44705058/e933d3b9-f1c5-40f2-b043-3d80b084adcc)

**Comment by nekomeowww** [comment]
Let me see. This is probably caused by `@nolebase/ui`.

**Comment by Ampernic** [comment]
> Let me see. This is probably caused by `@nolebase/ui`.

Thank you so much for fix <3

**Comment by nekomeowww** [comment]
> > Let me see. This is probably caused by `@nolebase/ui`.
> 
> 
> 
> Thank you so much for fix <3
> 
> Everything works perfectly

Sounds great! Thank you very much for feedbacks!
