### ISSUE TITLE
improve(git-changelog): support rewrite extensions

### ISSUE THREAD

**Issue by kwaa** [nolebase/integrations#158]
My docs using [Dynamic Routes](https://vitepress.dev/guide/routing#dynamic-routes), and I want to show the git changelog for the source file.

Basically like this: `packages/foo/bar/*.ts` => `foo/*.md`

I solved the folder part by configuring `rewritePaths`, but the extension couldn't be solved.

My repo: https://github.com/moeru-ai/hub

**Comment by nekomeowww** [comment]
Wonderful suggestion,

will that help if we add `rewritePathsByPatterns: Record<string, string>`, and suppprt `rewritePaths` as `(commit: Commit)=> string`？

**Comment by kwaa** [comment]
I'm not quite sure how the latter works, but the former should help.

Maybe support for full paths and RegExp?

**Comment by kwaa** [comment]
How about making it like [`editLink.pattern`](https://vitepress.dev/reference/default-theme-edit-link#site-level-config)?

```ts
GitChangelog({
  rewritePathsByPattern: ({ filePath }) => {
    if (filePath.startsWith('foo/')) {
      ...
    } else {
      ...
    }
  }
})
```

**Comment by LittleSound** [comment]
This idea is good. Let's write one.

**Comment by nekomeowww** [comment]
> How about making it like [editLink.pattern](https://vitepress.dev/reference/default-theme-edit-link#site-level-config)?

Yes sure, we can do that. Let me check the types and implementations for it.

**Comment by kwaa** [comment]
> Yes sure, we can do that. Let me check the types and implementations for it.

It's just a `(data) => string` function, with specific rewrite rules defined by the user within the function.

**Comment by nekomeowww** [comment]
Released as `2.0.0-rc2`, feel free to give it a try 🤭

**Comment by kwaa** [comment]
> Released as `2.0.0-rc2`, feel free to give it a try 🤭

How to use `rewritePathsBy.handler`?

It looks like it needs to return an `Awaitable<Commit>` instead of a `string`, which causes the `rewritePathsByRewritingExtension` that comes with the plugin to not work either.

https://github.com/nolebase/integrations/blob/577fcee10a604b0607bae6071ede8b0e0dc7234f/packages/vitepress-plugin-git-changelog/src/vite/git.ts#L24

https://github.com/nolebase/integrations/blob/577fcee10a604b0607bae6071ede8b0e0dc7234f/packages/vitepress-plugin-git-changelog/src/vite/git.ts#L99-L107

**Comment by nekomeowww** [comment]
@kwaa Ah, sorry I mis-declared the types, it will be handled as string internally instead of Commit. Please try to add a as any temporarily, or wait for me to release one more PR to fix this.

**Comment by nekomeowww** [comment]
@kwaa Yes, I found it. Thanks for finding the issue inside the source codes 🥺

**Comment by kwaa** [comment]
@nekomeowww Update: It looks like it only includes for markdown files. Maybe I should open a new issue?

https://github.com/nolebase/integrations/blob/ff7c14ba3ba922c1d791106bdc68aba65eef3f8d/packages/vitepress-plugin-git-changelog/src/vite/git.ts#L71-L82

**Comment by nekomeowww** [comment]
@kwaa hmmm, that was something I never thought about. I forgot here is a constraint for extension.

Yes, please open a new issue. And feel free to open up a pull request to fix it if you want.
