### ISSUE TITLE
improve(git-changelog): allow more extensions

### ISSUE THREAD

**Issue by kwaa** [nolebase/integrations#168]
https://github.com/nolebase/integrations/issues/158#issuecomment-2057228435

**Comment by nekomeowww** [comment]
Would you like to implement this issue?

**Comment by kwaa** [comment]
> Would you like to implement this issue?

I'll give it a try, but I'm not sure what configuration format you prefer.

**Comment by nekomeowww** [comment]
@kwaa How about adding one more option to allow users to specify what file extensions should be filtered out?

Then template these extensions into Regexp.

Not quite sure what the use cases are, can the option with default to .md, .mdx, .html enough?

Feel free to design and question me  since I may not understand your need very well.

**Comment by nekomeowww** [comment]
@kwaa How about adding one more option to allow users to specify what file extensions should be filtered out?

Then template these extensions into Regexp.

Not quite sure what the use cases are, can the option with default to .md, .mdx, .html enough?

Feel free to design and question me  since I may not understand your need very wellm

**Comment by kwaa** [comment]
> How about adding one more option to allow users to specify what file extensions should be filtered out?
> 
> Then template these extensions into Regexp.
> 
> Not quite sure what the use cases are, can the option with default to .md, .mdx, .html enough?
> 
> Feel free to design and question me since I may not understand your need very wellm

Then maybe `includeExtensions`?

Since VitePress doesn't support `.mdx` by default, I thought `.md` would be fine as the default.

But my needs are special: as mentioned before, I need to map the `*.ts` files in `packages/` to dynamic route pages.

```diff
  const {
    maxGitLogCount,
    maxConcurrentProcesses,
    includeDirs = [],
+   includeExtensions = [],
    repoURL = 'https://github.com/example/example',
    getReleaseTagURL = defaultReleaseTagURLHandler,
    getCommitURL = defaultCommitURLHandler,
  } = options
```

```diff
  log.path = Array.from(
    new Set(
      files
        .filter((i) => {
          // include is not set, it is /^.+\md$/
          // include is set, it is /^(${include.join('|')})\/.+\md$/
          // in another word, /^(includeItem1|includeItem2|includeItem3)\/.+\md$/
-         const regexp = new RegExp(`^${includeDirs.length > 0 ? `(${includeDirs.join('|')})${sep === win32.sep ? win32.sep : `\\${posix.sep}`}` : ''}.+\\.md$`)
+         const regexp = new RegExp(`^${includeDirs.length > 0 ? `(${includeDirs.join('|')})${sep === win32.sep ? win32.sep : `\\${posix.sep}`}` : ''}.+\\.${includeExtensions.length > 0 ? `(${includeExtensions.join('|')})` : '.md' }$`)
          return !!i[1]?.match(regexp)?.[0]
        }),
    ),
  )
```

**Comment by nekomeowww** [comment]
Nice design. Good enough.

Another thought is (out of the scope, maybe consider it as a deprecations): the `.md` constraint here is basically being a role of filtering out of logs for the purpose to reduce the computation it needs to be done when dealing with massive logs. And the `include*` isn't that much straightforward to understand at such circumstances, would that be better if we design another name for it?

**Comment by kwaa** [comment]
> would that be better if we design another name for it?

It would be better, but I don't have any suitable ideas.

**Comment by nekomeowww** [comment]
> It would be better, but I don't have any suitable ideas.

Let's keep it what it is for now.
