### ISSUE TITLE
Vitepress build error after update to 2.0.0-rc4

### ISSUE THREAD

**Issue by maks-oleksyuk** [nolebase/integrations#169]
Hi 👋, thanks for the great module and your work.

After updating the package to the new version and going through all the configuration file updates, I get the following error:
![image](https://github.com/nolebase/integrations/assets/90793591/4bd33771-0347-4a67-8d7c-3be1f4af1ed1)

I also tried to solve it by adding the following to the vite settings in the .vitepress/config file:
```json
build: {
    rollupOptions: {
        external: ['@nolebase/ui']
    }
},
```

But it just showed the next error:
![image](https://github.com/nolebase/integrations/assets/90793591/ef65c302-41b1-4785-bcc9-a693cb6a2977)

Any ideas or steps to solve this problem, I would really like to try the functionality from the new version.

**Comment by nekomeowww** [comment]
1. What build system are you using?
2. What is your configuration for Vite or other bundler?
3. What do you have for your package.json? Did you try to clean it up and try again?

**Comment by nekomeowww** [comment]
Issue identified. Please wait for the next rc release, should be released within 6 hours.
