### ISSUE TITLE
bug(git-changelog): invalid commit link

### ISSUE THREAD

**Issue by kwaa** [nolebase/integrations#179]
I've noticed that `git-changelog` plugin is generating invalid commit links, not sure what caused it.

https://nolebase-integrations.ayaka.io/pages/en/integrations/vitepress-plugin-git-changelog/#file-history

Meanwhile, nolebase with the old version `2.0.0-rc3` seems to be working fine. 

https://nolebase.ayaka.io/%E7%AC%94%E8%AE%B0/#%E6%96%87%E4%BB%B6%E5%8E%86%E5%8F%B2

**Comment by nekomeowww** [comment]
Possibly by #171
