### ISSUE TITLE
阅读增强插件 Layout 和内容宽度问题

### ISSUE THREAD

**Issue by mancuoj** [nolebase/integrations#190]
因为不太熟悉 Vue，想知道怎么能让官方那个 [View Transition API 的明暗切换按钮](https://vitepress.dev/guide/extending-default-theme#on-appearance-toggle) 和阅读增强插件一起使用，我将 [Layout 直接用于 h 函数](https://github.com/csfive/home/blob/main/.vitepress/theme/index.ts#L15) 不太行。

另外，开启最新版的阅读增强插件后，不会增加内容宽度，只有边栏会移动到两侧。

![GIF 2024-5-2 11-57-27](https://github.com/nolebase/integrations/assets/45707684/c4f9a61d-6858-4dbe-9e95-2fc9d5a12438)

**Comment by kwaa** [comment]
> 想知道怎么能让官方那个 [View Transition API 的明暗切换按钮](https://vitepress.dev/guide/extending-default-theme#on-appearance-toggle) 和阅读增强插件一起使用

可以参考[我的 Layout.vue](https://github.com/moeru-ai/hub/blob/57d0e2ddbe090eaf0287b2f3d166ddd07296ae58/docs/.vitepress/theme/Layout.vue#L44-L53)，在对应位置添加 slot。

**Comment by nekomeowww** [comment]
@mancuoj > 谢谢 @kwaa 的解答！

之前 @LittleSound 也给 rle.wiki 做过类似的集成。

核心在于这行：

https://github.com/project-trans/RLE-wiki/blob/main/docs/.vitepress/theme/index.ts#L32C5-L32C39

具体的 AppearanceToggle 在这里可以参考（大概率用不到，但方便你找资料所以在这里提及一下）

https://github.com/project-trans/RLE-wiki/blob/main/docs/.vitepress/theme/components/AppearanceToggle.vue

**Comment by mancuoj** [comment]
@nekomeowww @kwaa 感谢二位解答 ❤️

但是还有一个 Gif 里的问题不知道怎么解决，我看上文提到的 https://rle.wiki/campus/ 内容宽度是可以正常展开的，是[我配置](https://github.com/csfive/home/blob/main/.vitepress/config.ts#L52)哪里出了问题吗？

**Comment by nekomeowww** [comment]
@mancuoj 配置看着没问题。

你说的是 rle.wiki 是自动展开的，你的没有自动展开，对吗？
那你通过右上角的“书籍”图标选择不同的布局的时候，能展开吗？

如果是希望配置默认值，可以看一下     https://nolebase-integrations.ayaka.io/pages/zh-CN/integrations/vitepress-plugin-enhanced-readabilities/#%E9%85%8D%E7%BD%AE%E9%80%89%E9%A1%B9 介绍的配置内容，然后根据页面介绍的配置方案进行配置。

**Comment by mancuoj** [comment]
@nekomeowww https://csfive.netlify.app，可以打开看一下，就跟这个 gif 展示的一样，内容宽度没有展开

> 另外，开启最新版的阅读增强插件后，不会增加内容宽度，只有边栏会移动到两侧。
> 
> ![GIF 2024-5-2 11-57-27](https://private-user-images.githubusercontent.com/45707684/327306380-c4f9a61d-6858-4dbe-9e95-2fc9d5a12438.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NDg2NzAsIm5iZiI6MTcxNDY0ODM3MCwicGF0aCI6Ii80NTcwNzY4NC8zMjczMDYzODAtYzRmOWE2MWQtNjg1OC00ZGJlLTllOTUtMmZjOWQ1YTEyNDM4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDExMTI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxZjZhZDVjMTViNDU5MWU0MzE2NDkyODkxMzFmMjA1Y2JhYmNmNWM3MzlhMGQ2N2UzYzlkODQ1MzA0YTg0YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HcSjXX9gcSJ4p_ZRAMcIZGmYZPe_W1PzJnjnaAIyHXg) [ ![GIF 2024-5-2 11-57-27](https://private-user-images.githubusercontent.com/45707684/327306380-c4f9a61d-6858-4dbe-9e95-2fc9d5a12438.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NDg2NzAsIm5iZiI6MTcxNDY0ODM3MCwicGF0aCI6Ii80NTcwNzY4NC8zMjczMDYzODAtYzRmOWE2MWQtNjg1OC00ZGJlLTllOTUtMmZjOWQ1YTEyNDM4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDExMTI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxZjZhZDVjMTViNDU5MWU0MzE2NDkyODkxMzFmMjA1Y2JhYmNmNWM3MzlhMGQ2N2UzYzlkODQ1MzA0YTg0YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HcSjXX9gcSJ4p_ZRAMcIZGmYZPe_W1PzJnjnaAIyHXg) ](https://private-user-images.githubusercontent.com/45707684/327306380-c4f9a61d-6858-4dbe-9e95-2fc9d5a12438.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NDg2NzAsIm5iZiI6MTcxNDY0ODM3MCwicGF0aCI6Ii80NTcwNzY4NC8zMjczMDYzODAtYzRmOWE2MWQtNjg1OC00ZGJlLTllOTUtMmZjOWQ1YTEyNDM4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDExMTI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxZjZhZDVjMTViNDU5MWU0MzE2NDkyODkxMzFmMjA1Y2JhYmNmNWM3MzlhMGQ2N2UzYzlkODQ1MzA0YTg0YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HcSjXX9gcSJ4p_ZRAMcIZGmYZPe_W1PzJnjnaAIyHXg) [ ](https://private-user-images.githubusercontent.com/45707684/327306380-c4f9a61d-6858-4dbe-9e95-2fc9d5a12438.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NDg2NzAsIm5iZiI6MTcxNDY0ODM3MCwicGF0aCI6Ii80NTcwNzY4NC8zMjczMDYzODAtYzRmOWE2MWQtNjg1OC00ZGJlLTllOTUtMmZjOWQ1YTEyNDM4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDExMTI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxZjZhZDVjMTViNDU5MWU0MzE2NDkyODkxMzFmMjA1Y2JhYmNmNWM3MzlhMGQ2N2UzYzlkODQ1MzA0YTg0YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HcSjXX9gcSJ4p_ZRAMcIZGmYZPe_W1PzJnjnaAIyHXg)

**Comment by nekomeowww** [comment]
啊我理解了。抱歉我 miss 了你最开始的 GIF 了。我现在还在外面，回到家里稳定的时候我看一下你的项目配置。

我猜可能是和 VitePress 版本不兼容或者主题不兼容导致的。

**Comment by nekomeowww** [comment]
阅读增强插件不工作确认是因为与 VitePress 最新版本不兼容导致的，我会尽快在接下来的发布中修复和兼容 VitePress，但我会计划先发布包含了 #189 特性的 `2.0.0-rc11` 然后先确保支持了 `1.0.2`。

如果你希望先用上阅读增强插件，可以先暂时降级一下 VitePress（我会尽快修复）。

**Comment by mancuoj** [comment]
> 阅读增强插件不工作确认是因为与 VitePress 最新版本不兼容导致的，我会尽快在接下来的发布中修复和兼容 VitePress，但我会计划先发布包含了 #189 特性的 `2.0.0-rc11` 然后先确保支持了 `1.0.2`。
> 
> 如果你希望先用上阅读增强插件，可以先暂时降级一下 VitePress（我会尽快修复）。

了解，感谢。

**Comment by nekomeowww** [comment]
在最新的 rc12 中，我已经对齐了 VitePress 的最新版本，没有发现不兼容的问题。

不过根据 https://github.com/csfive/home/blob/bcc2341e2689ba6d19e571db4dff73fe4a9c1d01/.vitepress/theme/index.ts#L1-L9 这段代码声明，我觉得是因为导入优先级造成的，阅读增强插件是通过覆盖 VitePress 原始的样式实现的，在这段代码中，VitePress 的主题在阅读增强插件之后导入，因此造成了优先级不同的区别。

正确的做法是：

```diff
+import type { Theme as ThemeConfig } from 'vitepress'
+import DefaultTheme from 'vitepress/theme'
+import { h } from 'vue'
+
 import {
   NolebaseEnhancedReadabilitiesMenu,
   NolebaseEnhancedReadabilitiesScreenMenu,
 } from '@nolebase/vitepress-plugin-enhanced-readabilities/client'
-import '@nolebase/vitepress-plugin-enhanced-readabilities/client/style.css'
-import type { Theme as ThemeConfig } from 'vitepress'
-import DefaultTheme from 'vitepress/theme'
-import { h } from 'vue'
+
 import Layout from './components/Layout.vue'
+
+import '@nolebase/vitepress-plugin-enhanced-readabilities/client/style.css'
+
 import './styles/index.css'

export default {
  extends: DefaultTheme,
  Layout: () => {
    return h(Layout, null, {
      'nav-bar-content-after': () => h(NolebaseEnhancedReadabilitiesMenu),
      'nav-screen-content-after': () => h(NolebaseEnhancedReadabilitiesScreenMenu),
    })
  },
} satisfies ThemeConfig
```
