### ISSUE TITLE
fix: git-change-log, there are multiple names in the contributors list after i changed my github username

### ISSUE THREAD

**Issue by Glomzzz** [nolebase/integrations#199]
It looks like this:
![image](https://github.com/nolebase/integrations/assets/70137442/b6b6f3c1-fb66-42ea-a228-84acb2f1ea90)

I think this is due to Git itself, but I really want to fix it.

**Comment by nekomeowww** [comment]
Use `mapContributors` options.

**Comment by Glomzzz** [comment]
i see，tks
