### ISSUE TITLE
improve: simplify mapContributors configuration

### ISSUE THREAD

**Issue by northword** [nolebase/integrations#209]
目前的组件获取链接的逻辑是获取 GitHub 链接，但很多时候，我们希望显示个人主页（例如博客），或是一些网站的目标群体其实不是 GitHub ，所以会更希望显示为其他的平台链接，

我们是否有想法改为 

1. 获取 GitHub 链接，若有则返回，无 GitHub 且包含其他则返回第一个。
2. 直接返回第一个，如果用户需要始终显示 GitHub 的，手动把 map 数据里 GitHub 放在第一位就好。 

虽然可以把 GitHub 直接填成其他的，但是似乎不是那么 （规范？），并且无法解决 其他链接和 GitHub 同时放（比如团队页）的情况。

_Originally posted by @northword in https://github.com/nolebase/integrations/issues/197#issuecomment-2095882873_
            
---

此外，对于头像等，我们可以尝试  —— 首先尝试从 GitHub 获取（github username > name），如果 GitHub 不存在（github username 未设置且 name 与 github user name不一致），再从 gravatar 获取。

**Comment by nekomeowww** [comment]
可以的。
