### ISSUE TITLE
imporove: avoid bundling raw git logs

### ISSUE THREAD

**Issue by northword** [nolebase/integrations#223]
(不清楚在技术上是否可行

我想我们不应该把原始的 git log 信息也打包进 dist，因为除了“最后更新于xx天前”以外，其他的似乎都是纯静态的，不需要使用到原始 log，目前把所有的原始 log 打包，导致 theme.js 特别大，影响性能。

![image](https://github.com/nolebase/integrations/assets/44738481/25df849a-e6b3-4ca7-96ce-47c7ef1ae019)

**Comment by nekomeowww** [comment]
> (不清楚在技术上是否可行
> 
> 我想我们不应该把原始的 git log 信息也打包进 dist，因为除了“最后更新于xx天前”以外，其他的似乎都是纯静态的，不需要使用到原始 log，目前把所有的原始 log 打包，导致 theme.js 特别大，影响性能。

我觉得是可以的，可能得用 content data loader 或者 onServerPrefetch 解决。

实在不行的话就是改进 virtual module 潜入的方式，在 resolveId 的时候根据 moduleGraph resolve 成不同的 markdown path 的 virtual module，方便做 chunking。

然后得看看 VitePress 的 build time data loader 咋做的，可能他们不会需要嵌入数据？

**Comment by northword** [comment]
> 然后得看看 VitePress 的 build time data loader 咋做的，可能他们不会需要嵌入数据？

他们的也会嵌入数据，文档中有提到：

> > VitePress 提供了数据加载的功能，它允许加载任意数据并从页面或组件中导入它。数据加载只在构建时执行：最终的数据将被序列化为 JavaScript 包中的 JSON。

实测也是会把整个数据打包到 chunks 里（我就是因为写另一个功能时候发现 VitePress 的数据加载有这个问题，想参考一下 Git-changelog 插件的，才发现 commit log 也被打包了

**Comment by nekomeowww** [comment]
你有 Discord 吗？
我们可以到 Discord 里面更高效地讨论 https://discord.gg/XuNFDcDZGj

或者 Telegram 或者别的联系方式也可以。
