### ISSUE TITLE
bug (git-changelog, enhanced-readabilities): Problems with localization in `vitepress dev`

### ISSUE THREAD

**Issue by Ampernic** [nolebase/integrations#243]
**Setup:**
- `vitepress` - v1.2.3
- `@nolebase/vitepress-plugin-enhanced-readabilities` - 2.2.0
- `@nolebase/vitepress-plugin-git-changelog` - 2.2.0

**Problem:**
Before the build, in the "vitepress dev" mode, the date is incorrectly displayed and the "enhanced-readabilities" localization is not displayed, uses default.

https://github.com/nolebase/integrations/assets/44705058/dc05decc-0aa4-424b-af9c-0104abf770a3

(First tab - local with dev. Second - build deploy)

**Comment by Ampernic** [comment]
**GitLog Locales**
```ts
"ru-RU": {
        changelog: {
            title: "История изменений",
            noData: "Нет изменений",
            lastEdited: "Последнее редактирование: {{daysAgo}}",
            lastEditedDateFnsLocaleName: "ru",
            viewFullHistory: "Показать историю",
            committedOn: " от {{date}}"
        },
        contributors: {
            title: "Авторы",
            noData: "Нет информации"
        }
}
```

**enhanced-readabilities locales:**
https://github.com/OlegShchavelev/ALTGnomeWiki/blob/main/_data/enhanced-readabilities.ts

**Comment by nekomeowww** [comment]
Sorry for the delay. I am recovered from surgery in-patient for the past a few weeks.

> the "enhanced-readabilities" localization is not displayed, uses default.

<img width="444" alt="image" src="https://github.com/nolebase/integrations/assets/11081491/4909715e-4e83-4478-af68-bfc3e3ae4cc5">

I cannot reproduce the issue, do you have a minimal repro?

**Comment by Ampernic** [comment]
After update to @nolebase/vitepress-plugin-git-changelog to 2.2.1 date display correctly. Thx.

> > the "enhanced-readabilities" localization is not displayed, uses default.

> I cannot reproduce the issue, do you have a minimal repro?

Sorry, really my configuration error, after double-checking found the error.
