### ISSUE TITLE
Git changelog plugin enhancements

### ISSUE THREAD

**Issue by giladgd** [nolebase/integrations#252]
The git changelog plugin is awesome!

However, there are some small things about it that I'd like to be able to configure before I can adopt it in my Vitepress website:
1. For each line in the changelog, to be able to show the date as a relative time (e.g. `2 weeks ago`) instead of a fixed date 
  - #255
3. The ability to hide the Changelog `h2` header (so the changelog component will just appear at the bottom of the page with no title)
  - #256
5. The ability to show the contributor for each commit on the commit itself on the changelog
  - #258
7. The ability to hide the "sort by" button
  - #257
9. I use Vitepress' [`transformPageData`](https://vitepress.dev/reference/site-config#transformpagedata) to modify frontmatter for pages, and having the changelog plugin respect those changes would make it easier for me to disable or enable it for specific pages

Thanks for making this awesome plugin :)

**Comment by nekomeowww** [comment]
> I use Vitepress' [transformPageData](https://vitepress.dev/reference/site-config#transformpagedata) to modify frontmatter for pages, and having the changelog plugin respect those changes would make it easier for me to disable or enable it for specific pages.

What do you mean by `respect those changes would make it easier for me to disable or enable it`? You can always disable markdown affacted Nolebase plugins with

```yaml
nolebase:
  <pluginNameCamelCase>: false
```

For git-changelog plugin, it is stated here: https://nolebase-integrations.ayaka.io/pages/en/integrations/vitepress-plugin-git-changelog/configure-vite-plugins#excluding-a-page-from-the-transformation-of-gitchangelogmarkdownsection

Is this what you are expecting to have?

**Comment by giladgd** [comment]
In my `.vitepress/config.ts` file I have this code:
```typescript
export default defineConfig({
    transformPageData(pageData) {
        if (pageData.filePath.startsWith("api/")) {
            pageData.frontmatter.editLink = false;
            pageData.frontmatter.lastUpdated = false;
            pageData.frontmatter ||= {};
            pageData.frontmatter.outline = [2, 3];

            // This doesn't seem to affect the page
            pageData.frontmatter.nolebase = {
                gitChangelog: false
            };
        }
    }
})
```

The problem is that the changelog still appears on pages where this code should have disabled it

**Comment by nekomeowww** [comment]
I see. The git-changelog injected the markdown page too early at the time that the transformPageData hasn't been invoked yet. This might be a little bit tricky to deal with if you need to use `GitChangelogMarkdownSection`.

The only way to fix this is by manully mount and template the `NolebaseGitChangelog` and `NolebaseGitContributors` when creating the layout.

**Comment by nekomeowww** [comment]
Anyway, welcome to Nolebase community!

Thank you so much for the rest of the feature requests, I accepted them.
Should be able to ship them ASAP since they are not relatively hard to implement.

And always, feel free to ask any questions 😄

**Comment by taskylizard** [comment]
Adding on this issue thread, it would be nice if github avatars of commit authors will be used by default instead of manually mapping authors in config.

**Comment by nekomeowww** [comment]
> Adding on this issue thread, it would be nice if github avatars of commit authors will be used by default instead of manually mapping authors in config.

@northword was this even possible?

**Comment by nekomeowww** [comment]
@giladgd Btw, all accepted requests has been implemented and released. 
Sorry that I forgot to close this but this issue should already be closed.

cc @taskylizard we can move to another issue to discuss this further.

**Comment by taskylizard** [comment]
Sure thing, thanks!

**Comment by giladgd** [comment]
@nekomeowww Thank you for implementing everything :)
I've just tested it, and it works great!

I've opened a PR to use GitHub avatars when possible since I found that this is the main thing missing for me in the current implementation (#277)
