### ISSUE TITLE
feature request(git-changelog): add contributors to specific pages via frontmatter 

### ISSUE THREAD

**Issue by northword** [nolebase/integrations#259]
Due to some historical reasons, it may happen that some contributors are not recorded in Git, so we need to support displaying those contributors by specifying them in FrontMatter.

In my vision, it should work like this:

```md
---
authors?: 
  - name: string
    url?: string
  - name: string
    url?: string
---

<!-- text -->
```

- When frontmatter.authors exists, the authors in frontmatter are always displayed first, followed by those in the Git log. 
- If there are duplicates in frontmatter.authors and in the Git record, only one is shown. 
- Here frontmatter.authors should also go with mapContributors.

I'd be happy to implement it if that's okay.

**Comment by nekomeowww** [comment]
Should it be authors?

**Comment by northword** [comment]
> Should it be authors?

This is mainly influenced by other projects, e.g. [vuepress-theme-hope](https://theme-hope.vuejs.press/zh/config/frontmatter/info.html#author), but `authors` does work better with arrays.

**Comment by nekomeowww** [comment]
Ah, just curious. After a brief read through the page you mentioned, I think it is fine and an option for you to decide whether to have it called `author` or `authors`. In fact, even at the perspective point of developers, `authors` may be much more intuitive, but end users may not understand such a "convention" thou.

It's up to you. You can choose what ever you want.
