### ISSUE TITLE
feature request(git-changelog): use github authors avatars by default

### ISSUE THREAD

**Issue by northword** [nolebase/integrations#277]
> Adding on this issue thread, it would be nice if github avatars of commit authors will be used by default instead of manually mapping authors in config.

_Originally posted by @taskylizard in https://github.com/nolebase/integrations/issues/252#issuecomment-2253177129_

**Comment by northword** [comment]
Of course, it's achievable. Until the plugin implements it, maybe it could be done by mapping the array in `mapAuthors` and specifying a `username` for it?

**Comment by northword** [comment]
@taskylizard In addition, this feature must address the question of what we what to use as a GitHub username. Without clarifying this, we might get the wrong user avatar.

What we have now is a manually configured `username` field in `mapAuthors`, which by default matches the GitHub avatar when it exists.

The username and email can be read from the Git history, however, in my experience, many of the usernames in the commit history are not Git platform (e.g. GitHub) usernames.

**Comment by nekomeowww** [comment]
@northword Implementation reference: 

https://github.com/gitkraken/vscode-gitlens/pull/814

https://github.com/mhutchie/vscode-git-graph/commit/ee829d6c5ed826835d9b40a836063b5db72d8054

Related discussion:

https://github.com/gitkraken/vscode-gitlens/issues/281

https://github.com/gitkraken/vscode-gitlens/issues/1036

This looks quite complex to implement and support different data sources, and even valuable to have a dedicated package for more universal use cases.

**Comment by nekomeowww** [comment]
@northword Possibly related:

https://discord.com/channels/1229292283657195520/1229292844838162474/1245752865247727677

https://discord.com/channels/1229292283657195520/1229292844838162474/1243464211669979137

https://discord.com/channels/1229292283657195520/1229292844838162474/1245578360655057029
