### ISSUE TITLE
bug(inline-link-preview): style of external link

### ISSUE THREAD

**Issue by ghost** [nolebase/integrations#297]
When enabling the Inline link preview plugin in VitePress, there appears 2 arrows for external links.
The first arrow is provided by Inline-link-preview-plugin. The second arrow is provided by VitePress theme.
![image](https://github.com/user-attachments/assets/5fff4faa-840d-4d91-baf0-701d2f471f52)

Suggested scenario:
Disable the arrow provided by Inline-link-preview-plugin to avoid duplication of styles.
![image](https://github.com/user-attachments/assets/cea7f86f-8db5-4fa1-8427-322ca3e4fdd2)

**Comment by nekomeowww** [comment]
Completed and released already.
