### ISSUE TITLE
Unknown file extension `.vue` on production build when use `bun` as package manager

### ISSUE THREAD

**Issue by LemonNekoGH** [nolebase/integrations#301]
I got this error message after I applied plugin `@nolebase/vitepress-plugin-enhanced-readabilities` to `vitepress`.
```
bun run docs:build
$ vitepress build

  vitepress v1.3.4

✓ building client + server bundles...
build error:
Unknown file extension ".vue" for /Users/lemonneko/Projects/minimal-reproduction-code-nolebase-vitepress-plugin-enhanced-readabilities/node_modules/@nolebase/ui/dist/components/NuTag/index.vue
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".vue" for /Users/lemonneko/Projects/minimal-reproduction-code-nolebase-vitepress-plugin-enhanced-readabilities/node_modules/@nolebase/ui/dist/components/NuTag/index.vue
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:160:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:203:36)
    at defaultLoad (node:internal/modules/esm/load:143:22)
    at async ModuleLoader.load (node:internal/modules/esm/loader:396:7)
    at async ModuleLoader.moduleProvider (node:internal/modules/esm/loader:278:45)
error: script "docs:build" exited with code 1
```
Reproduction code: [minimal-reproduction-code-nolebase-vitepress-plugin-enhanced-readabilities.zip](https://github.com/user-attachments/files/16814794/minimal-reproduction-code-nolebase-vitepress-plugin-enhanced-readabilities.zip)

This error may caused by `bun` because when I replace `bun` to `pnpm`, this error has gone.

The version of `bun`:
```
bun --version
$ 1.1.24
```

**Comment by nekomeowww** [comment]
@LemonNekoGH Are there any StackBlitz like platforms for bun for me to better and quicker understand where went wrong?

And I am not sure how many compatiblities were supported by bun by comparing to pnpm & nodejs for module resolving and vite dependencies resolving.

**Comment by LemonNekoGH** [comment]
No, I can't find any StackBlitz like platforms for bun, so I can only provide minimal reproduction code in a compressed archive file 😭

**Comment by LemonNekoGH** [comment]
Maybe I need to read the source code of `bun`

**Comment by Kutius** [comment]
I'm using bun and @nolebase/vitepress-plugin-enhanced-readabilities. Everything is fine as of the latest version.
Bun: `v1.1.26`
Maybe I think missing configuration item here:
```json
    ssr: {
      noExternal: [
        '@nolebase/vitepress-plugin-enhanced-readabilities',
      ],
    },
```
