### ISSUE TITLE
docs: @nolebase/vitepress-plugin-inline-link-preview 

### ISSUE THREAD

**Issue by litingyes** [nolebase/integrations#308]
`@nolebase/vitepress-plugin-inline-link-preview` needs to be displayed to indicate that it needs to be added to `vite.ssr.noExternal`, or build error

**Comment by nekomeowww** [comment]
Indeed, I missed the vite config part for it. 

PR is welcomed.

You just need to copy & paste the following content:

https://github.com/nolebase/integrations/blob/a02e00395cdd32404cc934a3ff9045a05e670d9f/docs/pages/en/integrations/vitepress-plugin-enhanced-readabilities/index.md?plain=1#L71-L137

with slight adjustments then put them into:

https://github.com/nolebase/integrations/blob/main/docs/pages/en/integrations/vitepress-plugin-inline-link-preview/getting-started.md

**Comment by litingyes** [comment]
okk

**Comment by litingyes** [comment]
> Indeed, I missed the vite config part for it.
> 
> PR is welcomed.
> 
> You just need to copy & paste the following content:
> 
> https://github.com/nolebase/integrations/blob/a02e00395cdd32404cc934a3ff9045a05e670d9f/docs/pages/en/integrations/vitepress-plugin-enhanced-readabilities/index.md?plain=1#L71-L137
> 
> with slight adjustments then put them into:
> 
> https://github.com/nolebase/integrations/blob/main/docs/pages/en/integrations/vitepress-plugin-inline-link-preview/getting-started.md

done

**Comment by nekomeowww** [comment]
Thank you. Merged.
