### ISSUE TITLE
docs(breadcrumbs): twoslash error when build docs

### ISSUE THREAD

**Issue by northword** [nolebase/integrations#351]
Please see build log: https://github.com/nolebase/integrations/actions/runs/12046242309/job/33586316756#step:8:517

Seems introduced in https://github.com/nolebase/integrations/pull/330 
(log: https://github.com/nolebase/integrations/actions/runs/11894803033/job/33142863047#step:8:517 )

CC: @LemonNekoGH

**Comment by LemonNekoGH** [comment]
Thank you for found this issue！
