### ISSUE TITLE
bug: 阅读增强菜单未被激活时，内部的悬浮提示依然会被触发

### ISSUE THREAD

**Issue by Nisekoi5** [nolebase/integrations#47]
鼠标放置在问号所处的位置就会显示出来，哪怕菜单没有激活。在右侧导航点击的时候经常会出来
![cam](https://github.com/nolebase/integrations/assets/49276902/9a8fd7f8-ebac-4ff0-8cfd-8fa40d04cad1)
似乎是使用了opacity: 0;控制了菜单的显示，更改为 display:none 应该可以实施修复。

**Comment by Nisekoi5** [comment]
我直接在控制台加上居然也可以，样式在切换时添加的属性没有被覆盖掉
![nole](https://github.com/nolebase/integrations/assets/49276902/dc73c131-097a-497c-a549-200bfca1fa8a)

**Comment by nekomeowww** [comment]
@Nisekoi5 感谢你帮忙找到重现的方式 🥺

我之前一直好奇为什么有的时候会闪烁，一直没找到能好好复现的方式。

嗯，切换成 v-if 可能就好了，我没记错的话现在应该是 v-show 实现的

你要试试看修复一下吗？

**Comment by nekomeowww** [comment]
@Nisekoi5 应该是这个 isOutside 导致的

https://github.com/nolebase/integrations/blob/7ae7389e21aafaa5fc8ee3af02cf463fe8bf00e9/packages/vitepress-plugin-enhanced-readabilities/src/components/MenuHelp.vue#L19

我之前对这个 useMouseInElement （文档 https://vueuse.org/core/useMouseInElement/#usemouseinelement ）的理解不充分，它应该是无法判断出来元素是否可见的，尤其是在父元素没有传递相关的参数的情况下，父元素可见度为 0 的时候自然还会有相关的监听器发生作用（因为其实是判断的坐标点，最好是改成 Element Hover 的判断，很抱歉我之前疏忽了）

所以这个改起来应该是会有点难度，你也可以试试看，如果没时间的话我晚点就把这个修复了

**Comment by Nisekoi5** [comment]
> @Nisekoi5 应该是这个 isOutside 导致的
> 
> https://github.com/nolebase/integrations/blob/7ae7389e21aafaa5fc8ee3af02cf463fe8bf00e9/packages/vitepress-plugin-enhanced-readabilities/src/components/MenuHelp.vue#L19
> 
> 我之前对这个 useMouseInElement （文档 https://vueuse.org/core/useMouseInElement/#usemouseinelement ）的理解不充分，它应该是无法判断出来元素是否可见的，尤其是在父元素没有传递相关的参数的情况下，父元素可见度为 0 的时候自然还会有相关的监听器发生作用（因为其实是判断的坐标点，最好是改成 Element Hover 的判断，很抱歉我之前疏忽了）
> 
> 所以这个改起来应该是会有点难度，你也可以试试看，如果没时间的话我晚点就把这个修复了

把仓库拉下来试了下。不知道怎么调试这种插件😂 我编码是业余的，只会修能直接跑起来的，这种插件类型的包不知道怎么搞到vitepress中调试（改了会有反馈），还是让你有时间了来修吧

**Comment by nekomeowww** [comment]
@Nisekoi5 不用太担心需要把插件弄到 nolebase 或者 vitepress 里面哦

Nolebase Integrations 其实也有自己的文档（在 https://nolebase-integrations.ayaka.io ），这个文档就是开发的时候我们在本地会参考的前端界面，在代码仓库里位于 docs 目录下。

如果你想试试看的话，可以打开两个终端，分别监听插件的修改和 vitepress 的修改就好了 🥳

可以像这样操作：

1. 开一个终端/命令行界面，前往克隆的 nolebase/integrations 目录，然后运行
pnpm packages:dev

就可以监听众插件的变化啦，这个时候每次修改插件都会自动重新构建，然后触发 vitepress 的构建


2. 和之前一样，开一个终端/命令行界面，前往克隆的 nolebase/integrations 目录，然后运行
pnpm docs:dev

就可以监听 vitepress 的变化啦，打开 localhost:5173 就可以一边本地开发一边在浏览器预览

**Comment by Nisekoi5** [comment]
> 监听 vitepress 的变化啦，打开 localhost:5173 就可以一边本地开发一边在

原来是这样，改起来好像倒是不要几行。
一直想把外面的父元素改为display:none 发现好像行不通。这家伙是vitepress的组件。
这东西的用法只能自己看源码吗。我看官网似乎没有相关文档？ 
包括自己diy的组件想做出符合原版风格的样式好像也没有什么规范跟介绍的
以AppContainer改了个[小组件](https://note.loli.rs/%E7%AC%94%E8%AE%B0/%F0%9F%AA%84%20ACG/%F0%9F%93%B7%E6%BC%AB%E7%94%BB/%E6%9C%AA%E5%AE%8C%E7%BB%93%E6%BC%AB%E7%94%BB.html) 也不太敢修改样式怕太突兀 😵

**Comment by nekomeowww** [comment]
@Nisekoi5 > 这东西的用法只能自己看源码吗。我看官网似乎没有相关文档？

对的 🙃 他们相当于是想做开箱即用的文档构建器 + 自带默认主题，而这个默认主题里面的组件其实都不是很好地给外部用的（如果你用过诸如 Hexo 和 Hugo 这样的静态网站生成器应该就能理解，很多都是集成好的一整套前端界面而不是带组件的）

> 包括自己diy的组件想做出符合原版风格的样式好像也没有什么规范跟介绍的

这个确实没有什么文档会教，但我有一套自己已经总结成型的方法论：

1. 浮窗用类似的圆角，自带阴影
2. 任何组件都最好直接引用 vitepress 的 css 颜色变量
3. 多端适配，亮暗色适配也最好用 vitepress 的

Nolebase Integration 的代码其实都很简单呢，也可以看看里面有关 vp- 开头的 css 变量引用都是如何生效的

**Comment by nekomeowww** [comment]
@Nisekoi5 可以帮你 review 看看 👀

**Comment by nekomeowww** [comment]
> 以AppContainer改了个[小组件](https://note.loli.rs/%E7%AC%94%E8%AE%B0/%F0%9F%AA%84%20ACG/%F0%9F%93%B7%E6%BC%AB%E7%94%BB/%E6%9C%AA%E5%AE%8C%E7%BB%93%E6%BC%AB%E7%94%BB.html) 也不太敢修改样式怕太突兀 😵

看了看，发现我们都有一样的需求诶，我最近也在导入和写入我看过和玩过的电影，动漫，漫画，和游戏，也许我们可以一起添加一个新的模块到 nolebase integrations？或者单开一个 nolebase components 放这些有趣的组件。

我写了个半成品的列表来记录和索引这些记录，但是样式还没有设计好呢，感觉你通过 AppContainer 直接改的思路也挺有意思的 😂

AppContainer 我最早是想要学习 App Store 网页端的样子去收纳一些 App 的介绍，没想到还能阴差阳错地有这样的用途，夸夸 👍

**Comment by Nisekoi5** [comment]
> 看了看，发现我们都有一样的需求诶，我最近也在导入和写入我看过和玩过的电影，动漫，漫画，和游戏，也许我们可以一起添加一个新的模块到 nolebase integrations？或者单开一个 nolebase components 放这些有趣的组件。


这个功能可以有哈哈，是用啥方案啊填个链接/ID直接去`TMDB`之类的刮削元数据还是也自己手填啊。

本来打算再添加上`标签`,`集数`等数据的，但是感觉每个都这样手填起来太麻烦了就砍掉了这些不太重要的东西 QWQ

> 我写了个半成品的列表来记录和索引这些记录，但是样式还没有设计好呢，感觉你通过 AppContainer 直接改的思路也挺有意思的 😂

因为自己用就不用想那么多直接改组件，敏捷开发，快速上线（

**Comment by nekomeowww** [comment]
@Nisekoi5 > 这个功能可以有哈哈，是用啥方案啊填个链接/ID直接去`TMDB`之类的刮削元数据还是也自己手填啊。 

好主意诶，我之前都没这么想过，我想的都是自己复制出来 🤣（可能被众网站 404 弄怕了，害怕会没办法找到这些资源）
 
> 本来打算再添加上`标签`,`集数`等数据的，但是感觉每个都这样手填起来太麻烦了就砍掉了这些不太重要的东西 QWQ

没事哦，夸夸！能做到就很厉害了w
 
> 因为自己用就不用想那么多直接改组件，敏捷开发，快速上线（ 

确实，VitePress 就是这点比较好，能直接引用组件，想要什么样式都很简单
