### ISSUE TITLE
feature request: migrate og image generation from nolebase to nolebase/integrations

### ISSUE THREAD

**Issue by nekomeowww** [nolebase/integrations#92]
As title.

## What is og image generation?

First of all, og means [Open Graph Protocol](https://ogp.me/). @LittleSound designed an SVG template to render og images that [Nolebase](https://nolebase.ayaka.io) uses on Figma 2 years ago (I can't believe it's been 2 years, I feel like it was yesterday).

The SVG template is located at: [https://github.com/nolebase/nolebase/blob/main/scripts/og-template.svg](https://github.com/nolebase/nolebase/blob/main/scripts/og-template.svg)

Where it got read by [`post-doc.ts`](https://github.com/nolebase/nolebase/blob/5bccc5d0836cf3a45fc6b0b4eff7013e0b8bcd9e/scripts/post-docs.ts#L17) script.

The rendering mechanism works simple, it replaces template strings with the desired strings, that's it, yes. ([Code](https://github.com/nolebase/nolebase/blob/5bccc5d0836cf3a45fc6b0b4eff7013e0b8bcd9e/scripts/post-docs.ts#L85-L95))

## Why?

1. Nolebase now comes with its own scripts and components, which is not good, I want Nolebase to contain Markdown only, so these scripts and components from Nolebase need to be moved to Nolebase Integrations.
2. The library we're using now to render SVG as PNG is `sharp`, `sharp` is based on C++ and requires `node-gyp` to compile, then `sharp` also relies on `libxml` to do XML parsing (because SVG is XML so it needs to be parsed). While there are two users reported an error to https://github.com/nolebase/issues/26, saying that both Windows and macOS can't render SVG successfully. However, I don't know what to do to fix them since I cannot reproduce them by my self. This is because that `sharp` is not the one we chose, and @LittleSound copied from `vueuse.org` two years ago. `sharp` has all these pitfalls, therefore I'd like to replace it with `resvg` (which is also used by `vercel/satori`).
3. The current generation logic is not well developed. I want to be able to give the user an editor on the documentation page to choose their own colors, their own fonts and then download and save as a template to drag directly to the Nolebase folder and then use it!
4. There is no way to configure fonts in `sharp` right now. That means, if you use CI/CD to render SVGs directly in GitHub Actions, Chinese will be rendered as 口口口 due to missing system fonts, which is not very good. (`resvg` can specify the font in options, this is another reason though).

## How?

- Simply create one separated package, write a vite plugin to help to perform og images after build (using `buildEnd` book).
- To create the needed package, simply copy & paste the existing vitepress plugin and you are free to go (you will still need knowledge about how monorepo works though).

**Comment by luoling8192** [comment]
好耶~
